[advisories]
yanked = "deny"

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "MPL-2.0",
    "Unlicense",
    "BSL-1.0",
    "0BSD",
    "OFL-1.1",
    "Ubuntu-font-1.0",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
skip = [
    { name = "bitflags" },
    { name = "calloop" },
    { name = "calloop-wayland-source" },
    { name = "core-foundation" },
    { name = "getrandom" },
    { name = "hashbrown" },
    { name = "jni-sys" },
    { name = "linux-raw-sys" },
    { name = "objc2" },
    { name = "objc2-app-kit" },
    { name = "objc2-foundation" },
    { name = "redox_syscall" },
    { name = "rustix" },
    { name = "smithay-client-toolkit" },
    { name = "thiserror" },
    { name = "thiserror-impl" },
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]

[[licenses.clarify]]
name = "sublime_fuzzy"
expression = "Apache-2.0"
license-files = [{ path = "LICENSE", hash = 0 }]

